name: Elixir CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: 1.10.2 # Define the elixir version [required]
        otp-version: 22 # Define the OTP version [required]
    - name: Install Dependencies
      run: cd kv && mix deps.get
    - name: Check formatting
      run: cd kv && mix format --check-formatted
    - name: Run Tests
      run: cd kv && mix test
